### ISSUE TITLE
fails when I chmod my executable

### ISSUE THREAD

**Issue by AskAlice** [jiro4989/build-rpm-action#2]
run: https://github.com/section/sectionctl/runs/2753815209?check_suite_focus=true
workflow file: https://github.com/section/sectionctl/actions/runs/909778761/workflow

if i remove the chmod +x line it succeeds.

**Comment by jiro4989** [comment]
I think that `chmod` is not a error reason.
Does it fail when re-run jobs?

**Comment by AskAlice** [comment]
the only real difference between these two jobs is I chmodded my executable.

https://github.com/section/sectionctl/actions/runs/909604715/workflow
https://github.com/section/sectionctl/actions/runs/909778761/workflow

It seems it is related to this issue:
https://github.com/rpm-software-management/rpm/issues/367
https://github.com/rpm-software-management/rpm/issues/367#issuecomment-350131349

**Comment by jiro4989** [comment]
You built executables on ubuntu-latest VM.
build-rpm-actions uses centos 7 images.
Please build executables on centos 7 docker container or build staticly.

**Comment by jiro4989** [comment]
static build and use build-rpm-action example

https://www.github.com/jiro4989/textimg/tree/master/.github%2Fworkflows%2Frelease.yml
