### ISSUE TITLE
%post spec section

### ISSUE THREAD

**Issue by surfzoid** [jiro4989/build-rpm-action#7]
Hi
could yu please add an input to add to your spec template an post section, customisation of other section should be welcome.

My rpm spec file, need : 

%post
ln -s $(whereis "libopenal.so.1" | sed "s|.* \(.*libopenal.so.1\).*|\1|") /usr/lib64/QtVsPlayer/

I thank you

**Comment by surfzoid** [comment]
i think, if you provide me the correct path of the template i can use sed or other standar shell cmd to add the section before build

**Comment by jiro4989** [comment]
@surfzoid I added a `post` parameter. Please use it.
https://github.com/jiro4989/build-rpm-action/blob/d803488448e25fcf2d89376d86adab0c6b443448/.github/workflows/test.yml#L81

**Comment by surfzoid** [comment]
i thank you, after my request here, i discover my post made an uninstall bug and so added also a preun as it

`
%post
if [ -f "%{_libdir}/QtVsPlayer/libopenal.so.1" ];
 then
    rm -fr %{_libdir}/QtVsPlayer/libopenal.so.1
fi
ln -s $(whereis "libopenal.so.1" | sed "s|.* \(.*libopenal.so.1\).*|\1|") %{_libdir}/QtVsPlayer/

%preun
if [ -f "%{_libdir}/QtVsPlayer/libopenal.so.1" ];
 then
    rm -fr %{_libdir}/QtVsPlayer/libopenal.so.1
fi`

I also discover you use a docker img, debian have the rpmbuild package, i use it with my self runner PI400  and increase speed: 
https://github.com/surfzoid/QtVsPlayer/blob/main/.github/workflows/c-cpp.yml

**Comment by surfzoid** [comment]
sudo apt-file find bin/rpmbuild
rpm: /usr/bin/rpmbuild

**Comment by jiro4989** [comment]
So, have you resolved yourself?

**Comment by surfzoid** [comment]
> So, have you resolved yourself?

finaly yes, it will be more flexible, thank yu

**Comment by jiro4989** [comment]
OK 👍
